FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG APP_VERSION
ARG VITE_AZURE_AD_TENANT_ID
ARG VITE_AZURE_AD_CLIENT_ID
ARG VITE_AZURE_AD_REDIRECT_URI
ENV APP_VERSION=${APP_VERSION}
ENV VITE_AZURE_AD_TENANT_ID=${VITE_AZURE_AD_TENANT_ID}
ENV VITE_AZURE_AD_CLIENT_ID=${VITE_AZURE_AD_CLIENT_ID}
ENV VITE_AZURE_AD_REDIRECT_URI=${VITE_AZURE_AD_REDIRECT_URI}

RUN npm run build

FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
