CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  company_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'offline',
  bio TEXT NOT NULL DEFAULT '',
  avatar TEXT NOT NULL DEFAULT 'default',
  banner TEXT NOT NULL DEFAULT 'default',
  is_managed_profile BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(email, company_id, event_id),
  UNIQUE(username, company_id, event_id)
);
CREATE TABLE IF NOT EXISTS user_contact_preferences (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  preferences JSONB NOT NULL DEFAULT '{"favorites":[],"categories":[],"assignments":{},"layout":"status"}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS friend_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recipient_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'accepted', 'declined')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(sender_id, recipient_id)
);
CREATE INDEX IF NOT EXISTS idx_friend_requests_recipient ON friend_requests(recipient_id, status);

CREATE TABLE IF NOT EXISTS conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  direct_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(company_id, event_id, direct_key)
);
CREATE TABLE IF NOT EXISTS conversation_members (
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY(conversation_id, user_id)
);
CREATE TABLE IF NOT EXISTS messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  draw_attention BOOLEAN NOT NULL DEFAULT FALSE,
  winks BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS unread_messages (
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(conversation_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, id);
CREATE INDEX IF NOT EXISTS idx_conversation_members_user ON conversation_members(user_id, conversation_id);
CREATE INDEX IF NOT EXISTS idx_users_scope ON users(company_id, event_id);

CREATE TABLE IF NOT EXISTS event_music_folders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  name TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 80),
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_event_music_folders_shared_name
  ON event_music_folders(company_id,event_id,lower(name)) WHERE owner_id IS NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_event_music_folders_personal_owner
  ON event_music_folders(owner_id) WHERE owner_id IS NOT NULL AND deleted_at IS NULL;
CREATE TABLE IF NOT EXISTS event_music_tracks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  video_id TEXT NOT NULL CHECK (video_id ~ '^[A-Za-z0-9_-]{11}$'),
  title TEXT NOT NULL,
  artist TEXT NOT NULL DEFAULT '',
  contributor_id INTEGER NOT NULL REFERENCES users(id),
  folder_id INTEGER REFERENCES event_music_folders(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  removed_at TIMESTAMPTZ,
  removed_by INTEGER REFERENCES users(id)
);
ALTER TABLE event_music_tracks ADD COLUMN IF NOT EXISTS folder_id INTEGER REFERENCES event_music_folders(id);
INSERT INTO event_music_folders(company_id,event_id,name)
  SELECT DISTINCT u.company_id,u.event_id,'Improving' FROM users u
  WHERE NOT EXISTS(SELECT 1 FROM event_music_folders f WHERE f.company_id=u.company_id AND f.event_id=u.event_id)
  ON CONFLICT DO NOTHING;
UPDATE event_music_tracks t SET folder_id=f.id FROM event_music_folders f
  WHERE t.folder_id IS NULL AND f.owner_id IS NULL AND f.deleted_at IS NULL
    AND f.name='Improving' AND f.company_id=t.company_id AND f.event_id=t.event_id;
ALTER TABLE event_music_tracks ALTER COLUMN folder_id SET NOT NULL;
DROP INDEX IF EXISTS idx_event_music_tracks_active_video;
CREATE UNIQUE INDEX IF NOT EXISTS idx_event_music_tracks_active_video
  ON event_music_tracks(folder_id, video_id) WHERE removed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_event_music_tracks_scope_order
  ON event_music_tracks(company_id, event_id, id) WHERE removed_at IS NULL;

CREATE TABLE IF NOT EXISTS user_music_preferences (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  share_activity BOOLEAN NOT NULL DEFAULT FALSE,
  revision BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE user_music_preferences ADD COLUMN IF NOT EXISTS revision BIGINT NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS user_music_activities (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL,
  socket_id TEXT NOT NULL DEFAULT '',
  client_sequence BIGINT NOT NULL,
  track_id INTEGER NOT NULL REFERENCES event_music_tracks(id),
  title TEXT NOT NULL,
  artist TEXT NOT NULL DEFAULT '',
  revision BIGINT NOT NULL DEFAULT 1,
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPTZ NOT NULL
);
ALTER TABLE user_music_activities ADD COLUMN IF NOT EXISTS socket_id TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_user_music_activities_expiry ON user_music_activities(expires_at);
CREATE TABLE IF NOT EXISTS user_music_session_sequences (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL,
  client_sequence BIGINT NOT NULL,
  PRIMARY KEY(user_id, session_id)
);

CREATE TABLE IF NOT EXISTS admin_users (
  email TEXT PRIMARY KEY,
  added_by TEXT NOT NULL DEFAULT 'system',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS user_presence_days (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  PRIMARY KEY(user_id, day)
);
CREATE INDEX IF NOT EXISTS idx_user_presence_days_day ON user_presence_days(day);

CREATE TABLE IF NOT EXISTS fotolog_profiles (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  theme JSONB NOT NULL DEFAULT '{}'
);
CREATE TABLE IF NOT EXISTS fotolog_posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  image TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  day DATE NOT NULL,
  UNIQUE(user_id,day)
);
CREATE TABLE IF NOT EXISTS fotolog_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES fotolog_posts(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS fotolog_comments_post ON fotolog_comments(post_id,created_at);
CREATE TABLE IF NOT EXISTS fotolog_favorites (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  favorite_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY(user_id,favorite_id),
  CHECK(user_id <> favorite_id)
);

-- Preserve the verified mail account name separately from the MSN nickname.
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_managed_profile BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS fotolog_urls (
  slug TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS fotolog_addresses (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  slug TEXT NOT NULL REFERENCES fotolog_urls(slug) ON DELETE CASCADE
);
