const english = {
  "Director de zumbidos": "Chief Nudge Officer",
  "Campanita humana": "Human Notification Bell",
  "La persona que más nudges envió.": "The person who sent the most nudges.",
  "La persona que más nudges recibió.": "The person who received the most nudges.",
  "Todavía no hay nudges": "No nudges yet",
  "nudges": "nudges",
  "Panel de administración": "Admin panel",
  "Cargando datos…": "Loading data…",
  "Actualizando…": "Refreshing…",
  "Actualizar": "Refresh",
  "Volver al Messenger": "Back to Messenger",
  "Salir": "Sign out",
  "Esta cuenta no tiene permisos de administración. Iniciá sesión con una cuenta Microsoft autorizada.": "This account does not have admin access. Sign in with an authorized Microsoft account.",
  "Cambiar de cuenta": "Switch account",
  "Cerrar aviso": "Dismiss notification",
  "Usuarios": "Users",
  "personas con cuenta": "people with an account",
  "Usuarios online por día": "Daily online users",
  "Personas distintas que se conectaron, últimos 14 días": "Unique people who connected over the last 14 days",
  "Hoy": "Today",
  "Estadísticas curiosas": "Fun statistics",
  "Canciones agregadas": "Songs added",
  "Nudges enviados": "Nudges sent",
  "Mensajes enviados": "Messages sent",
  "Amistades creadas": "Friendships created",
  "vez": "time",
  "veces": "times",
  "Sin winks aún": "No winks yet",
  "Wink más usado": "Most popular wink",
  "Carpetas de música compartidas": "Shared music folders",
  "Carpetas compartidas de la música": "Shared music folders",
  "Reintentar": "Retry",
  "No hay carpetas compartidas.": "No shared folders yet.",
  "Eliminar": "Delete",
  "Sí, eliminar": "Yes, delete",
  "Playlist compartida": "Shared playlist",
  "Cargando canciones…": "Loading songs…",
  "La playlist está vacía.": "The playlist is empty.",
  "Quitar": "Remove",
  "Sí, quitar": "Yes, remove",
  "Administradores": "Administrators",
  "Pueden ver este panel, gestionar la playlist y sumar o quitar admins.": "Can access this panel, manage playlists, and add or remove admins.",
  "Vos": "You",
  "Fundador": "Founder",
  "Sumar administrador": "Add administrator",
  "nombre.apellido@improving.com": "first.last@improving.com",
  "Agregar": "Add",
  "Tiene que entrar con esa cuenta de Microsoft para acceder.": "They must sign in with that Microsoft account to access the panel.",
  "Cancelar": "Cancel",
  "Confirmar": "Confirm",
  "Usuarios distintos conectados por día durante los últimos 14 días": "Unique users connected each day over the last 14 days",
  "Todavía no hay datos: el registro diario empieza desde que se activó este panel.": "No data yet: daily tracking starts when this panel is enabled.",
  "El número del día es la cantidad de usuarios distintos que se conectaron.": "Each day shows the number of unique users who connected.",
  "No se pudieron cargar las métricas. Si acabás de actualizar, volvé a desplegar el servidor y recargá la página.": "Could not load metrics. If you just updated the app, redeploy the server and reload the page.",
  "No se pudieron cargar las carpetas compartidas. Intentá de nuevo.": "Could not load shared folders. Please try again.",
  "No se pudo completar la acción. Intentá de nuevo.": "Could not complete the action. Please try again.",
  "Ingresá un email válido.": "Enter a valid email address.",
  "El dominio de ese email no está permitido.": "That email domain is not allowed.",
  "Esa persona ya es administradora.": "This person is already an administrator.",
  "Los administradores fundadores no se pueden quitar.": "Founding administrators cannot be removed.",
  "No podés quitarte a vos mismo.": "You cannot remove yourself.",
  "Esa persona ya no es administradora.": "This person is no longer an administrator.",
  "Esa canción ya no está en la playlist.": "This song is no longer in the playlist.",
  "Esa carpeta ya no existe.": "This folder no longer exists.",
  "Actualizado {time}": "Updated {time}",
  "Sin contar {count} cuentas de prueba (emails que incluyen “test”).": "Excludes {count} test accounts (emails containing “test”).",
  "{count} carpeta activa. Eliminarlas las quita para todos.": "{count} active folder. Deleting it removes it for everyone.",
  "{count} carpetas activas. Eliminarlas las quita para todos.": "{count} active folders. Deleting them removes them for everyone.",
  "{count} canción activa. Quitarla la elimina para todos.": "{count} active song. Removing it removes it for everyone.",
  "{count} canciones activas. Quitarla la elimina para todos.": "{count} active songs. Removing them removes them for everyone.",
  "agregada por": "added by",
  "alguien": "someone",
  "{email} ahora es administrador.": "{email} is now an administrator.",
  "{email} ya no es administrador.": "{email} is no longer an administrator.",
  "\"{title}\" se quitó de la playlist.": "\"{title}\" was removed from the playlist.",
  "\"{name}\" se eliminó para todos.": "\"{name}\" was deleted for everyone.",
  "Idioma del panel": "Panel language"
};

export const adminLocale = (language = 'en') => language === 'es' ? 'es-AR' : 'en-US';
export function adminCopy(text, language = 'en', values = {}) {
  const template = language === 'es' ? text : english[text] || text;
  return template.replace(/\{(\w+)\}/g, (match, key) => String(values[key] ?? match));
}
